/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storedbexample;

import storedbexample.model.Order;

/**
 *
 * @author fabouchedid
 */
public class OrderPanel extends javax.swing.JPanel {
       
    public OrderPanel() {
        initComponents();
    }
    
    public void setOrder(Order order) {        
        orderIdLabel.setText(order.getId());
        orderNameLabel.setText(order.getName());
        orderDateLabel.setText(order.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderIdLabel = new javax.swing.JLabel();
        orderNameLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 3));

        orderIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderIdLabel.setText("jLabel1");
        add(orderIdLabel);

        orderNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderNameLabel.setText("jLabel2");
        add(orderNameLabel);

        orderDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderDateLabel.setText("jLabel3");
        add(orderDateLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JLabel orderNameLabel;
    // End of variables declaration//GEN-END:variables
}
