/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storedbexample;

import java.sql.SQLException;
import java.util.List;
import storedbexample.database.OrderTable;
import storedbexample.model.Order;

public class OrdersPanel extends javax.swing.JPanel {

    public OrdersPanel() {
        initComponents();
        
    }
    
    public void setUserId(String userId) throws SQLException {
        this.removeAll();
        
        List<Order> orders = OrderTable.getUserOrders(userId);
        for(Order order: orders) {
            OrderPanel orderPanel = new OrderPanel();
            orderPanel.setOrder(order);
            this.add(orderPanel);
        }
        
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(5, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
