/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storedbexample;

import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import storedbexample.database.UserTable;
import storedbexample.model.User;

/**
 *
 * @author fabouchedid
 */
public class UsersPanel extends javax.swing.JPanel {
    
    public UsersPanel() {
        initComponents();
        List<User> users;
        try {
            users = UserTable.getAllUsers();
            for(User user: users) {
                UserPanel userPanel = new UserPanel();
                userPanel.setUser(user);
                this.add(userPanel);            
            }
        
            this.validate();
        } catch (SQLException ex) {  
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(10, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
